# Node.js
# Build and deploy Node.js web app to Azure Web App

trigger:
- main
- dev

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    webAppName: 'pawsomeplayback'
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    webAppName: 'pawsomeplayback-dev'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-student-connection'
    appName: $(webAppName)
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Deploy to Azure Web App'